### ISSUE TITLE
how to prepare modelnet40 dataset?

### ISSUE THREAD

**Issue by Xjunjiang** [aboulch/ConvPoint#1]
Hello, thank you very much for your work, and I want to know how to prepare modelnet40 dataset, is it directly download from https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip website?

**Comment by aboulch** [comment]
Hello,
I think I took this archive:
http://modelnet.cs.princeton.edu/ModelNet40.zip
Tell me if it works.

**Comment by aboulch** [comment]
Hello,
I made the modification to use https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip, it makes the code way more efficient.
Thanks for noticing.

**Comment by Xjunjiang** [comment]
Think you!
