### ISSUE TITLE
question about the low mIoU for npm3d dataset

### ISSUE THREAD

**Issue by amiltonwong** [aboulch/ConvPoint#11]
Hi, @aboulch ,

I had followed the training [steps](https://github.com/aboulch/ConvPoint/tree/master/examples/npm3d) for npm3d. However, after the final epoch (99), the IOU only reaches to `38.948` ([log](https://gist.github.com/amiltonwong/ff7061fe3dd58b8ec8fd747585ad4203)), which is far less than `75.9` reported in your paper? What are the reasons? Also, could you release the original trained model for comparison?

THX!

**Comment by aboulch** [comment]
Hi,
This kind of problem may be related to non-contiguous array passed to the knn library.
I made an update past week, adding `.ascontiguousarray()` in the .pyx of the library.
I am trying to make it more robust.

Tell me if the problem persists.

**Comment by amiltonwong** [comment]
@aboulch , thanks for your reply. The IOU is increased after adding .ascontiguousarray() in the .pyx
