### ISSUE TITLE
How to get the m

### ISSUE THREAD

**Issue by zhrjzrj** [aboulch/ConvPoint#15]

**Comment by zhrjzrj** [comment]
I just want to know the performance of the trained model , but I find that the test dataset doesn't have its' label, so how can I get the result like this http://semantic3d.net/view_results.php?chl=1

**Comment by aboulch** [comment]
Hello,
Sorry for this very late response.
To get these results you need to submit to the benchmark.
Another method would be to split the train set into new_train/val, retrain the model on the new_train set and evaluate on the custom validation set. It would not be the definitive results but can give you a rough estimation of the performance.
