### ISSUE TITLE
Inference time on custom dataset

### ISSUE THREAD

**Issue by aravind3134** [aboulch/ConvPoint#16]
Hello,

I am trying to use conv_point on custom dataset. In the process, I converted point cloud to text and label files (the format of semantic-8 dataset) and was able to train successfully. It took 21 hours for training ~90 million points on 4 classes for 50 epochs. But, when I try to infer a point cloud(~50 million points)on the same machine, it shows the estimated time is almost 150 hours. 

I went back to test a site from semantic-8 datatset(one with 30 million points), the same machine could do it in 71 seconds. Am I missing anything here? 

Thanks in advance.

**Comment by renwang435** [comment]
Are you able to successfully write the semantic-8 point clouds? Could you share the function parameters you ran that benchmark with?

**Comment by aboulch** [comment]
Hello,
Very sorry for late response.
To reduce the inference time, the parameter is `test_step`.
It is the step to translate the test column. If this parameter is small the columns will overlap, the prediction will be more confident (several prediction for each point) but slower. If the parameter if large (e.g. same of `block_size`), the test will be faster.
