### ISSUE TITLE
Nearest neighbor module  error!

### ISSUE THREAD

**Issue by missbook520** [aboulch/ConvPoint#22]
hi !  Thanks for your work!
when I bulid the Nearest neighbor module and run test .py ,but i get the confusing result ,like [[[25769803779 ,5 ,0]]] ,and i set the K parameter equal to 3 ,i want to know why I  get the so big data(trash data) 
![1](https://user-images.githubusercontent.com/48777650/82402337-bb804280-9a8e-11ea-93ac-e45f194b57f5.png)
![22](https://user-images.githubusercontent.com/48777650/82402351-c1762380-9a8e-11ea-8af4-49f38220d93d.png)

**Comment by Asher-1** [comment]
this module does not support windows I think

**Comment by aboulch** [comment]
Hello sorry for late response,
As @Asher-1 said, the code has not been tested on Windows.
On Ubuntu, the folowing code seems to work:
`
batch_size = 1
num_points = 10
K = 3
pc = np.random.rand(batch_size, num_points, 3).astype(np.float32)
queries = np.ones((1,1,3), dtype=np.float32)
neigh_idx = nearest_neighbors.knn_batch(pc, queries, K, omp=True)
print("Queries", queries.shape)
print("PC", pc.shape)
print("Indices", neigh_idx.shape)`

**Comment by missbook520** [comment]
yeah,this work in ubuntu,thank you,Asher-1 and  aboulch
