### ISSUE TITLE
Data preparation for Semantic3D

### ISSUE THREAD

**Issue by mwussow** [aboulch/ConvPoint#23]
Dear Alexandre,

first of all thanks for your amazing research and this great library!
I am struggleling with running the Semantic3D code, probably because the data preparation only partly works on my system (Google Colab). The voxelization of raw data does not run stable (some files are created correctly, others are empty (this is seemingly random, because raw data are provided for both those that run correctly and those that fail and they are saved in the same folder).

Could you provide access to a processed dataset for Semantic3D by any chance?

I am looking forward to hear from you.

Best,
Moritz

**Comment by aboulch** [comment]
Hello,
I made modifications on the preparation code. It should point out if there is a problem with missing files.
