### ISSUE TITLE
Implementing Modelnet40 ,error no utils.metrics found

### ISSUE THREAD

**Issue by shangguan9191** [aboulch/ConvPoint#26]
Dear Author,

Sorry, i am new to this.
when i try implementing your pretrained model this error occurs.  I follow the procedure, clone the repo, download the data into repo and set directory.  Do i need do extra import for utils as well?

here you can find my code for issue: https://github.com/shangguan91/thesis-problems/blob/master/Modelnet40_isssue.ipynb

**Comment by aboulch** [comment]
Hello,
The reason for this error is the missing relative import at the begining of the modelnet40 example.
You can either import manually the utils folder or copy paste the functions in your notebook.
(I need to clean this part of the code, it is messy)
