### ISSUE TITLE
what is Input_pts ?

### ISSUE THREAD

**Issue by shangguan9191** [aboulch/ConvPoint#27]
Dear  Author, 

I have 3D point Cloud dataset of form:  Data(pos=[10240, 3], y=[1]) .
I am really confused of the input_pts. 

what would be the best way to implement your model? 

transfrom my data? rewrite the achiecture and forward pass, and training loop?

**Comment by aboulch** [comment]
Hello,
In this code, the input_pts are the points coodinates => pos in your case.
