### ISSUE TITLE
ModuleNotFoundError: No module named 'global_tags'

### ISSUE THREAD

**Issue by ywyue** [aboulch/ConvPoint#3]
Thanks for your network! May I ask you a question? When I ran the code 
python3 modelnet_classif.py --rootdir /home/ywyue/UA/3D DeepLearning/ModelNet40/modelnet40_ply_hdf5_2048
It reports an error: 
File "/home/ywyue/UA/3D DeepLearning/ConvPoint/layers/conv.py", line 7, in <module>
    from global_tags import GlobalTags
ModuleNotFoundError: No module named 'global_tags'

So I wonder where the 'global_tags' is. Besides, I use Python 3.7, and pytorch 1.1.0.
Thank you.

**Comment by aboulch** [comment]
Hello,
Sorry for that, missing file.
Should be OK now.

**Comment by ywyue** [comment]
It works now! Thank you very much!

**Comment by fre3ak** [comment]
Hello @ywyue  I am facing a similar problem on google colab, how did you resolve yours please
