### ISSUE TITLE
Predicted labels for semantic3D are mixed up

### ISSUE THREAD

**Issue by ntvy95** [aboulch/ConvPoint#35]
I use [this mapping](https://github.com/intel-isl/Open3D-PointNet2-Semantic3D/blob/master/util/point_cloud_util.py) to colourize the segmented point cloud for visualization. The visualization result of bildstein_station1_xyz_intensity_rgb_voxels is shown as below:

![image](https://user-images.githubusercontent.com/13184614/103476244-51d35f80-4df7-11eb-980d-054919be8d71.png)

Here the buildings are labelled as 4 (green, low vegetation) instead of 5 (red, building), and the trees are labelled as 2 (maroon, natural terrain) instead of 3 (fuchisia, high vegetation).

May I ask what did I might possibly go wrong here?

Thank you very much.

**Comment by ntvy95** [comment]
Oh, I realize that the [N_CLASSES = 8](https://github.com/aboulch/ConvPoint/blob/master/examples/semantic3d/semantic3d_seg_fusion.py) instead of N_CLASSES = 9 (counting the class 0 - unlabeled points). Is that the reason?

**Comment by aboulch** [comment]
Hello,
That's it !

**Comment by ntvy95** [comment]
Thank you for your confirmation!
