### ISSUE TITLE
How to train on my own data?

### ISSUE THREAD

**Issue by ywyue** [aboulch/ConvPoint#5]
Hi, Thanks for your great work. I have .las format dataset which has x, y, z, intensity and classification fields. I wonder how I can train the network on my own data? Thanks. Looking forward to your reply.

**Comment by aboulch** [comment]
Hello,
I think in order to do so, you must modify the data loading par in the s3dis_seg.py file. This class should load and select the points. Then the network you create will have only on channel for intensity.

**Comment by ywyue** [comment]
Hey, thanks for your reply! I am still confused about something. 
1.Could you explain 'only on channel for intensity' in more detail? I think intensity data is one training feature as different objects have different intensity, right? 
2.Your network converts ModelNet40 and ShapeNet40 to hdf5 file before training the data. So do I need to convert my .las file to hdf5 file too? 
Thanks for your help~

**Comment by aboulch** [comment]
Hello :
1) It would be a creation of the network with 1 channel (similar to grey value images):
     `net = Net(input_channels=1, output_channels=N_CLASSES)`
2) No HDF5 was only for easy use. You can load directly the data, you can start from the `s3dis_seg.py` example and modify the `PartDatasetTrainVal` class to train your own network

**Comment by ywyue** [comment]
Much appreciated :) I will give it a try.
