### ISSUE TITLE
Semantic Dataset

### ISSUE THREAD

**Issue by anuhya24** [aboulch/ConvPoint#6]
Hi Alexandre,

I have gone through your paper. Great work. I would like to know when you will be providing code related to Semantic dataset as i am currently working on data similar to that. It would be of great help to me

**Comment by yulongyu** [comment]
I also want this part of the code related to Semantic dataset。

**Comment by amiltonwong** [comment]
+1 Waiting for code for Semantic3D

**Comment by aboulch** [comment]
Hello,
Sorry for late response, I am finishing an extended version of the paper + code.
I shall be able to provide the code for both NPM3D and Semantic3D by mid-September (may be before).

**Comment by Sajjadmanal** [comment]
@aboulch I was looking for NPM3D as your name was mentioned at their site.

**Comment by aboulch** [comment]
Hello,
I released the code along with major reorganization of the folders.
