### ISSUE TITLE
Unable to build nearest_neighbors

### ISSUE THREAD

**Issue by Sajjadmanal** [aboulch/ConvPoint#7]
Hi,

Thanks for this wonderful project. 
I am facing issue while I try to build nearest neighbors.
I use the below command:
`python setup.py install --home="."`

It gives me the below error:
> running install
> running build
> running build_ext
> skipping 'knn.cpp' Cython extension (up-to-date)
> building 'nearest_neighbors' extension
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -I./ -IC:\Users\sm50014\AppData\Local\Continuum\anaconda3\envs\lidar\include -IC:\Users\sm50014\AppData\Local\Continuum\anaconda3\envs\lidar\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpknn.cpp /Fobuild\temp.win-amd64-3.6\Release\knn.obj -std=c++11 -fopenmp
> cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
> cl : Command line warning D9002 : ignoring unknown option '-fopenmp'
> knn.cpp
> knn.cpp(612): fatal error C1083: Cannot open include file: 'numpy/arrayobject.h': No such file or directory
> error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by aboulch** [comment]
Hello,
The provided code was tested on Ubuntu 16.04 and 18.04. The compiler was GCC, I am not sure that these commands in the setup.py can work with MSVC (until now I do not work with Windows).

May be try : 
`setup.py build --compiler=msvc`

One workaround might be Linux subsystem for windows and use the library as if were working with Linux.

**Comment by Sajjadmanal** [comment]
@aboulch It didn't work.

Although, I changed the setup.py with below code and it worked:

```
from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext
import numpy




ext_modules = [Extension(
       "nearest_neighbors",
       sources=["knn.pyx", "knn_.cxx",],  # source file(s)
       include_dirs=["./", numpy.get_include()],
       language="c++",            
       extra_compile_args = [ "-std=c++11", "-fopenmp",],
       extra_link_args=["-std=c++11", '-fopenmp'],
  )]

setup(
    name = "KNN NanoFLANN",
    ext_modules = ext_modules,
    cmdclass = {'build_ext': build_ext},
)
```

**Comment by aboulch** [comment]
Hello,
I changed the setup.py according to your file.

**Comment by yaping222** [comment]
Hi aboulch, 
I got a similar error:
Semantic3D.cpp:612:31: fatal error: numpy/arrayobject.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
When I run:
python setup.py install --home="."
under 'semantic3D_utils' folder.
I change 'include_dirs=["./"],' to 'include_dirs=["./", numpy.get_include()],' in setup.py, but it didn't work. 
Could you give some suggestions on how to solve this?
