### ISSUE TITLE
question about training on s3dis dataset

### ISSUE THREAD

**Issue by amiltonwong** [aboulch/ConvPoint#9]
Hi, @aboulch ,

From [here](https://github.com/aboulch/ConvPoint/tree/master/examples/s3dis), it is mentioned the training can be performed as 
`python s3dis_seg.py --rootdir path_to_data_processed/ --area 2 --savedir path_to_save_directory`. But it only trains for area 2. If we want to perform the training in a more general way: training on area 1,2,3,4,6. Does your code support on this? Or any further modifications on code are required?

THX!

**Comment by aboulch** [comment]
Hello,
It should be sufficient to change `--area 2` to `--area 3` or any area you want to use.
Tell me if everything is fine.

**Comment by amiltonwong** [comment]
@aboulch , thanks for your reply.
But it still uses only an individual area. In fact, I want to train area 1,2,3,4,6 all together. Does your code support `--area 1,2,3,4,6` training all together?

**Comment by aboulch** [comment]
Actually the is such that is you use `--area 1`, it will train with area 2,3,4,5 and 6 and test on area 1.
so if you want to test on area 5, just use the flag `--area 5` (it will train on 1,2,3,4 and 6).

**Comment by amiltonwong** [comment]
@aboulch , thanks a lot for such clarification.
